"""add original_price to services

Revision ID: 75dc00d2f987
Revises: 4c05076eeed7
Create Date: 2026-08-09 00:43:08.431129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75dc00d2f987'
down_revision: Union[str, None] = '4c05076eeed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('original_price', sa.Float(), nullable=True))
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.drop_constraint('user_addresses_user_id_fkey', 'user_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'user_addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_addresses', type_='foreignkey')
    op.create_foreign_key('user_addresses_user_id_fkey', 'user_addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.alter_column('user_addresses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('services', 'original_price')
    # ### end Alembic commands ###
