"""Add OrderGroup and Cart features

Revision ID: e3890c5557e0
Revises: 75dc00d2f987
Create Date: 2026-08-11 20:38:10.457774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3890c5557e0'
down_revision: Union[str, None] = '75dc00d2f987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_groups',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('order_group_id', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('actual_start_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'order_groups', ['order_group_id'], ['id'])
    op.add_column('payments', sa.Column('order_group_id', sa.String(length=100), nullable=True))
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'payments', ['order_group_id'])
    op.create_foreign_key(None, 'payments', 'order_groups', ['order_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'order_group_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'actual_start_time')
    op.drop_column('bookings', 'order_group_id')
    op.drop_table('order_groups')
    # ### end Alembic commands ###
